apiVersion: v1
kind: Service
metadata:
  name: addactivityservice-service
spec:
  type: ClusterIP
  selector:
    app: addactivityservice
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002